permalink: /notes/:year/:month/:day/:title
markdown: kramdown

baseurl: ""  # or baseurl: "/your-repo-name" if using a project page
url: "https://NikolaosFrantzeskakis.github.io"  # replace with your actual GitHub Pages URL

google_analytics: UA-105759743-1

plugins:
  - jekyll-feed
  - jekyll-seo-tag

