baseurl: ""  # Leave empty if using custom domain at root
url: "https://www.nikolaosfrantzeskakis.com"  # Your custom domain

google_analytics: UA-105759743-1

plugins:
  - jekyll-feed
  - jekyll-seo-tag
